export const SONGS: Record<number, { title: string; artist: string }> = {
  1: { title: "One", artist: "U2" },
  2: { title: "Billie Jean", artist: "Michael Jackson" },
  3: { title: "Three Little Birds", artist: "Bob Marley" },
  4: { title: "Sweet Child O' Mine", artist: "Guns N' Roses" },
  5: { title: "Mambo No. 5", artist: "Lou Bega" },
  6: { title: "Bohemian Rhapsody", artist: "Queen" },
  7: { title: "7 Nation Army", artist: "The White Stripes" },
  8: { title: "Eight Days a Week", artist: "The Beatles" },
  9: { title: "Love Potion No. 9", artist: "The Searchers" },
  10: { title: "Hotel California", artist: "Eagles" },
  11: { title: "Smells Like Teen Spirit", artist: "Nirvana" },
  12: { title: "Wonderwall", artist: "Oasis" },
  13: { title: "Superstition", artist: "Stevie Wonder" },
  14: { title: "Livin' on a Prayer", artist: "Bon Jovi" },
  15: { title: "I Will Always Love You", artist: "Whitney Houston" },
  16: { title: "Sweet Little Sixteen", artist: "Chuck Berry" },
  17: { title: "Dancing Queen", artist: "ABBA" },
  18: { title: "Stairway to Heaven", artist: "Led Zeppelin" },
  19: { title: "19", artist: "Adele" },
  20: { title: "Respect", artist: "Aretha Franklin" },
  21: { title: "21 Guns", artist: "Green Day" },
  22: { title: "22", artist: "Taylor Swift" },
  23: { title: "Crazy in Love", artist: "Beyoncé" },
  24: { title: "24K Magic", artist: "Bruno Mars" },
  25: { title: "Thriller", artist: "Michael Jackson" },
  26: { title: "Don't Stop Believin'", artist: "Journey" },
  27: { title: "Purple Rain", artist: "Prince" },
  28: { title: "Imagine", artist: "John Lennon" },
  29: { title: "Born to Run", artist: "Bruce Springsteen" },
  30: { title: "Like a Rolling Stone", artist: "Bob Dylan" },
  31: { title: "Under Pressure", artist: "Queen & David Bowie" },
  32: { title: "Lose Yourself", artist: "Eminem" },
  33: { title: "Hey Jude", artist: "The Beatles" },
  34: { title: "I Gotta Feeling", artist: "Black Eyed Peas" },
  35: { title: "Shake It Off", artist: "Taylor Swift" },
  36: { title: "Africa", artist: "Toto" },
  37: { title: "Take On Me", artist: "a-ha" },
  38: { title: "Blinding Lights", artist: "The Weeknd" },
  39: { title: "Mr. Brightside", artist: "The Killers" },
  40: { title: "Happy", artist: "Pharrell Williams" },
  41: { title: "Rolling in the Deep", artist: "Adele" },
  42: { title: "Uptown Funk", artist: "Bruno Mars" },
  43: { title: "Somebody That I Used to Know", artist: "Gotye" },
  44: { title: "Shape of You", artist: "Ed Sheeran" },
  45: { title: "Old Town Road", artist: "Lil Nas X" },
  46: { title: "Bad Guy", artist: "Billie Eilish" },
  47: { title: "Shallow", artist: "Lady Gaga" },
  48: { title: "Despacito", artist: "Luis Fonsi" },
  49: { title: "Watermelon Sugar", artist: "Harry Styles" },
  50: { title: "Levitating", artist: "Dua Lipa" },
  51: { title: "Drivers License", artist: "Olivia Rodrigo" },
  52: { title: "Stay", artist: "The Kid Laroi & Justin Bieber" },
  53: { title: "Sunflower", artist: "Post Malone" },
  54: { title: "God's Plan", artist: "Drake" },
  55: { title: "Sicko Mode", artist: "Travis Scott" },
  56: { title: "Rockstar", artist: "Post Malone" },
  57: { title: "Closer", artist: "The Chainsmokers" },
  58: { title: "Can't Stop the Feeling", artist: "Justin Timberlake" },
  59: { title: "Havana", artist: "Camila Cabello" },
  60: { title: "Thunder", artist: "Imagine Dragons" },
  61: { title: "Perfect", artist: "Ed Sheeran" },
  62: { title: "Attention", artist: "Charlie Puth" },
  63: { title: "New Rules", artist: "Dua Lipa" },
  64: { title: "When I Was Your Man", artist: "Bruno Mars" },
  65: { title: "Stitches", artist: "Shawn Mendes" },
  66: { title: "Route 66", artist: "Nat King Cole" },
  67: { title: "Can't Help Falling in Love", artist: "Elvis Presley" },
  68: { title: "Toxic", artist: "Britney Spears" },
  69: { title: "Summer of '69", artist: "Bryan Adams" },
  70: { title: "Stayin' Alive", artist: "Bee Gees" },
  71: { title: "September", artist: "Earth, Wind & Fire" },
  72: { title: "I Want It That Way", artist: "Backstreet Boys" },
  73: { title: "Wannabe", artist: "Spice Girls" },
  74: { title: "No Scrubs", artist: "TLC" },
  75: { title: "Bye Bye Bye", artist: "NSYNC" },
  76: { title: "Crazy", artist: "Gnarls Barkley" },
  77: { title: "Umbrella", artist: "Rihanna" },
  78: { title: "Poker Face", artist: "Lady Gaga" },
  79: { title: "Hips Don't Lie", artist: "Shakira" },
  80: { title: "Yeah!", artist: "Usher" },
  81: { title: "In Da Club", artist: "50 Cent" },
  82: { title: "Gold Digger", artist: "Kanye West" },
  83: { title: "Since U Been Gone", artist: "Kelly Clarkson" },
  84: { title: "Mr. Blue Sky", artist: "ELO" },
  85: { title: "Eye of the Tiger", artist: "Survivor" },
  86: { title: "Jessie's Girl", artist: "Rick Springfield" },
  87: { title: "Come On Eileen", artist: "Dexys Midnight Runners" },
  88: { title: "Every Breath You Take", artist: "The Police" },
  89: { title: "Girls Just Want to Have Fun", artist: "Cyndi Lauper" },
  90: { title: "Ice Ice Baby", artist: "Vanilla Ice" },
  91: { title: "All Star", artist: "Smash Mouth" },
  92: { title: "Jump", artist: "Van Halen" },
  93: { title: "Creep", artist: "Radiohead" },
  94: { title: "No Diggity", artist: "Blackstreet" },
  95: { title: "Gangsta's Paradise", artist: "Coolio" },
  96: { title: "Killing Me Softly", artist: "Fugees" },
  97: { title: "Virtual Insanity", artist: "Jamiroquai" },
  98: { title: "99 Problems", artist: "Jay-Z" },
  99: { title: "99 Luftballons", artist: "Nena" },
};

export function getSong(num: number) {
  return SONGS[num];
}
